insert into Marcas (id, nombre) values (1, 'BMW');
insert into Marcas (id, nombre) values (2, 'Saab');
insert into Marcas (id, nombre) values (3, 'Hyundai');
insert into Marcas (id, nombre) values (4, 'Nissan');
insert into Marcas (id, nombre) values (5, 'Volvo');
insert into Marcas (id, nombre) values (6, 'Isuzu');
insert into Marcas (id, nombre) values (7, 'Toyota');
insert into Marcas (id, nombre) values (8, 'Cadillac');
insert into Marcas (id, nombre) values (9, 'Acura');
insert into Marcas (id, nombre) values (10, 'Volkswagen');
insert into Marcas (id, nombre) values (11, 'Chevrolet');
insert into Marcas (id, nombre) values (12, 'Mazda');
insert into Marcas (id, nombre) values (13, 'GMC');
insert into Marcas (id, nombre) values (14, 'Mitsubishi');
insert into Marcas (id, nombre) values (15, 'Toyota');
insert into Marcas (id, nombre) values (16, 'Chevrolet');
insert into Marcas (id, nombre) values (17, 'Mazda');
insert into Marcas (id, nombre) values (18, 'Honda');
insert into Marcas (id, nombre) values (19, 'Audi');
insert into Marcas (id, nombre) values (20, 'Subaru');

insert into Coches (id, color, modelo, marca_id) values (1, 'Aquamarine', 'Pathfinder', 10);
insert into Coches (id, color, modelo, marca_id) values (2, 'Fuscia', 'Boxster', 4);
insert into Coches (id, color, modelo, marca_id) values (3, 'Aquamarine', 'Intrigue', 8);
insert into Coches (id, color, modelo, marca_id) values (4, 'Khaki', 'Solara', 3);
insert into Coches (id, color, modelo, marca_id) values (5, 'Teal', 'Explorer', 2);
insert into Coches (id, color, modelo, marca_id) values (6, 'Mauv', 'V90', 7);
insert into Coches (id, color, modelo, marca_id) values (7, 'Fuscia', 'TSX', 4);
insert into Coches (id, color, modelo, marca_id) values (8, 'Crimson', 'Roadrunner', 12);
insert into Coches (id, color, modelo, marca_id) values (9, 'Purple', 'Mark VIII', 15);
insert into Coches (id, color, modelo, marca_id) values (10, 'Blue', '300', 8);
insert into Coches (id, color, modelo, marca_id) values (11, 'Pink', 'Entourage', 2);
insert into Coches (id, color, modelo, marca_id) values (12, 'Puce', '4000', 20);
insert into Coches (id, color, modelo, marca_id) values (13, 'Khaki', 'Ridgeline', 13);
insert into Coches (id, color, modelo, marca_id) values (14, 'Red', 'Sunbird', 11);
insert into Coches (id, color, modelo, marca_id) values (15, 'Blue', 'Beretta', 19);
insert into Coches (id, color, modelo, marca_id) values (16, 'Green', 'Cruze', 3);
insert into Coches (id, color, modelo, marca_id) values (17, 'Fuscia', 'GL-Class', 17);
insert into Coches (id, color, modelo, marca_id) values (18, 'Teal', 'Achieva', 14);
insert into Coches (id, color, modelo, marca_id) values (19, 'Indigo', 'Wrangler', 11);
insert into Coches (id, color, modelo, marca_id) values (20, 'Purple', 'APV', 3);
insert into Coches (id, color, modelo, marca_id) values (21, 'Mauv', 'Cavalier', 9);
insert into Coches (id, color, modelo, marca_id) values (22, 'Maroon', 'Altima', 10);
insert into Coches (id, color, modelo, marca_id) values (23, 'Turquoise', 'DB9', 6);
insert into Coches (id, color, modelo, marca_id) values (24, 'Orange', 'CC', 17);
insert into Coches (id, color, modelo, marca_id) values (25, 'Goldenrod', 'Mirage', 20);
insert into Coches (id, color, modelo, marca_id) values (26, 'Aquamarine', '5 Series', 4);
insert into Coches (id, color, modelo, marca_id) values (27, 'Turquoise', 'Xterra', 5);
insert into Coches (id, color, modelo, marca_id) values (28, 'Yellow', 'Yukon XL 1500', 20);
insert into Coches (id, color, modelo, marca_id) values (29, 'Crimson', 'Outback', 2);
insert into Coches (id, color, modelo, marca_id) values (30, 'Goldenrod', 'Taurus', 11);
insert into Coches (id, color, modelo, marca_id) values (31, 'Crimson', 'Gran Sport', 15);
insert into Coches (id, color, modelo, marca_id) values (32, 'Maroon', '6000', 3);
insert into Coches (id, color, modelo, marca_id) values (33, 'Goldenrod', '9-5', 15);
insert into Coches (id, color, modelo, marca_id) values (34, 'Red', 'Corvette', 6);
insert into Coches (id, color, modelo, marca_id) values (35, 'Khaki', 'Suburban 1500', 16);
insert into Coches (id, color, modelo, marca_id) values (36, 'Goldenrod', 'Mustang', 2);
insert into Coches (id, color, modelo, marca_id) values (37, 'Yellow', 'LS', 8);
insert into Coches (id, color, modelo, marca_id) values (38, 'Goldenrod', 'Aurora', 6);
insert into Coches (id, color, modelo, marca_id) values (39, 'Orange', 'LX', 11);
insert into Coches (id, color, modelo, marca_id) values (40, 'Teal', 'G6', 2);
insert into Coches (id, color, modelo, marca_id) values (41, 'Maroon', 'Montero', 5);
insert into Coches (id, color, modelo, marca_id) values (42, 'Purple', 'Probe', 19);
insert into Coches (id, color, modelo, marca_id) values (43, 'Blue', 'Yukon', 2);
insert into Coches (id, color, modelo, marca_id) values (44, 'Pink', 'Boxster', 6);
insert into Coches (id, color, modelo, marca_id) values (45, 'Yellow', 'Sentra', 17);
insert into Coches (id, color, modelo, marca_id) values (46, 'Fuscia', 'TrailBlazer', 8);
insert into Coches (id, color, modelo, marca_id) values (47, 'Turquoise', 'Century', 12);
insert into Coches (id, color, modelo, marca_id) values (48, 'Mauv', '88', 9);
insert into Coches (id, color, modelo, marca_id) values (49, 'Puce', 'Aero 8', 9);
insert into Coches (id, color, modelo, marca_id) values (50, 'Mauv', 'E250', 5);

